"""
Django settings for QwertySite project.

Generated by 'django-admin startproject' using Django 2.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
with open('etc/secret_key.txt') as f:
 SECRET_KEY = f.read().strip()

# TESTING
DEBUG = True
ALLOWED_HOSTS = []
# PRODUCTION
#DEBUG = False
#ALLOWED_HOSTS = ['www.qwertyscans.com','qwertyscans.com','18.218.111.245']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
  
    'reader.apps.ReaderConfig',
    'accounts.apps.AccountsConfig',
    'pages.apps.PagesConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'QwertySite.urls'

TEMPLATES = [{
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [os.path.join(BASE_DIR, 'templates')],
    'APP_DIRS': True,
    'OPTIONS': {
       'context_processors': [
       'django.template.context_processors.debug',
       'django.template.context_processors.request',
       'django.contrib.auth.context_processors.auth',
       'django.contrib.messages.context_processors.messages',
        ],
    },
}]

WSGI_APPLICATION = 'QwertySite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases
with open('etc/db.txt') as f:
  dbEngine = f.readline().strip()
  dbName = f.readline().strip()
  dbUser = f.readline().strip()
  dbPassword = f.readline().strip()
DATABASES = {
  'default': {
      'ENGINE': dbEngine,
        'NAME': dbName,
        'USER': dbUser,
        'PASSWORD': dbPassword,
        'HOST': 'localhost',
        'PORT': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# PRODUCTION
# CSRF_COOKIE_SECURE = True
# SESSION_COOKIE_SECURE = True
# SECURE_CONTENT_TYPE_NOSNIFF = True
# SECURE_BROWSER_XSS_FILTER = True
# SECURE_SSL_REDIRECT = True
# X_FRAME_OPTIONS = 'DENY'

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

#TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

# TESTING
EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
EMAIL_FILE_PATH = '.'

# PRODUCTION
# STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
#
# emHost = ""
# emPort = ""
# emHostUser  = ""
# emHostPw = ""
# fromEmail = ""
# toEmail = ""
# with open('etc/email.txt') as f:
#   fromEmail = f.readline().strip()
#   toEmail = f.readline().strip()
#   emHost = f.readline().strip()
#   emPort = f.readline().strip()
#   emHostUser = f.readline().strip()
#   emHostPw = f.readline().strip()
# EMAIL_HOST = emHost
# EMAIL_PORT = emPort
# EMAIL_HOST_USER = emHostUser
# EMAIL_HOST_PASSWORD = emHostPw
# EMAIL_USE_TLS = True
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#
# DEFAULT_FROM_EMAIL = fromEmail
# SERVER_EMAIL = fromEmail
