# Generated by Django 2.0.1 on 2018-01-15 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.DecimalField(decimal_places=2, max_digits=5)),
                ('title', models.CharField(max_length=200)),
                ('num_pages', models.PositiveSmallIntegerField()),
                ('upload_date', models.DateTimeField(verbose_name='date uploaded')),
                ('storage_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('alternative_titles', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('language', models.CharField(max_length=100)),
                ('genres', models.CharField(max_length=100)),
                ('joints', models.CharField(max_length=200)),
                ('pic_location', models.CharField(max_length=200)),
                ('storage_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('storage_name', models.CharField(max_length=100)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.Chapter')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='manga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.Manga'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
