# Generated by Django 2.0.1 on 2018-01-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='manga',
            new_name='chapter',
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='manga',
            name='alternative_titles',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='manga',
            name='artist',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='manga',
            name='genres',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='manga',
            name='joints',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='manga',
            name='language',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
