# Generated by Django 2.0.1 on 2018-01-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_auto_20180115_0604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='number',
            new_name='chap_number',
        ),
        migrations.AddField(
            model_name='chapter',
            name='sort_number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter',
            name='vol_number',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
