# Generated by Django 2.0.1 on 2018-01-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0003_auto_20180115_0639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='storage_name',
        ),
        migrations.AddField(
            model_name='manga',
            name='status',
            field=models.CharField(choices=[(0, 'Completed'), (1, 'Current'), (2, 'Hiatus'), (3, 'Dropped'), (4, 'Future')], default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chapter',
            name='upload_date',
            field=models.DateTimeField(editable=False, verbose_name='date uploaded'),
        ),
    ]
