# Generated by Django 2.0.1 on 2018-01-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0004_auto_20180115_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(max_length=200, upload_to=''),
        ),
    ]
