# Generated by Django 2.0.1 on 2018-01-17 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0006_auto_20180116_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='display_method',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Traditional (pages)'), (1, 'Webtoon (strip view)')], default=1),
        ),
    ]
