# Generated by Django 2.0.1 on 2018-01-17 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0007_manga_display_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='user',
            new_name='owner',
        ),
    ]
