# Generated by Django 2.0.1 on 2018-01-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0008_auto_20180117_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='artist',
            field=models.CharField(max_length=50),
        ),
    ]
