# Generated by Django 2.0.1 on 2018-01-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0009_auto_20180117_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='displayed',
            field=models.BooleanField(default=True),
        ),
    ]
