# Generated by Django 2.0.1 on 2018-01-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0011_auto_20180126_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='is_joint',
            field=models.BooleanField(default=False),
        ),
    ]
