# Generated by Django 2.0.1 on 2018-01-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0012_manga_is_joint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='status',
            field=models.CharField(choices=[('CP', 'Completed'), ('CU', 'Current'), ('HT', 'Hiatus'), ('DP', 'Dropped'), ('FT', 'Future')], default='CU', max_length=2),
        ),
    ]
