# Generated by Django 2.0.1 on 2018-01-25 07:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_blogpost_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 25, 7, 57, 29, 493144, tzinfo=utc), editable=False, verbose_name='date'),
        ),
    ]
