# Generated by Django 2.0.1 on 2018-01-26 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20180125_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('AN', 'Annoucements'), ('RE', 'Releases')], default='RE', max_length=2),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
